/*
 * Gestion des ingrédients API
 * API pour la gestion des ingrédients (TD Spring Boot)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.TD5.spring.java.org.openapitools.client.api;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.openapitools.client.ApiException;
import org.openapitools.client.model.IngredientsIdGet200Response;
import org.openapitools.client.model.IngredientsIdStockGet200Response;

import java.time.OffsetDateTime;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Récupérer un ingrédient par son identifiant
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ingredientsIdGetTest() throws ApiException {
        Long id = null;
        IngredientsIdGet200Response response = api.ingredientsIdGet(id);
        // TODO: test validations
    }

    /**
     * Récupérer la valeur de stock d&#39;un ingrédient à une date donnée
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ingredientsIdStockGetTest() throws ApiException {
        Long id = null;
        OffsetDateTime at = null;
        String unit = null;
        IngredientsIdStockGet200Response response = api.ingredientsIdStockGet(id, at, unit);
        // TODO: test validations
    }

}
