/*
 * Gestion des ingrédients API
 * API pour la gestion des ingrédients (TD Spring Boot)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.TD5.spring.java.org.openapitools.client.model;

import org.junit.Test;
import org.openapitools.client.model.IngredientsIdGet200Response;

/**
 * Model tests for IngredientsIdGet200Response
 */
public class IngredientsIdGet200ResponseTest {
    private final IngredientsIdGet200Response model = new IngredientsIdGet200Response();

    /**
     * Model tests for IngredientsIdGet200Response
     */
    @Test
    public void testIngredientsIdGet200Response() {
        // TODO: test IngredientsIdGet200Response
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

}
