/*
 * Gestion des ingrédients API
 * API pour la gestion des ingrédients (TD Spring Boot)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.TD5.spring.java.org.openapitools.client.model;

import org.junit.jupiter.api.Test;
import org.openapitools.client.model.IngredientsIdStockGet200Response;

/**
 * Model tests for IngredientsIdStockGet200Response
 */
public class IngredientsIdStockGet200ResponseTest {
    private final IngredientsIdStockGet200Response model = new IngredientsIdStockGet200Response();

    /**
     * Model tests for IngredientsIdStockGet200Response
     */
    @org.testng.annotations.Test
    public void testIngredientsIdStockGet200Response() {
        // TODO: test IngredientsIdStockGet200Response
    }

    /**
     * Test the property 'unit'
     */
    @Test
    public void unitTest() {
        // TODO: test unit
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
